### ISSUE TITLE
Something with update_by

### ISSUE THREAD

**Issue by michail1982** [jamierumbelow/codeigniter-base-model#108]
Class test extends Controller {
   function index() {
      $this->user_model->update_by(
          array('div_id'=>1),
          array('job_id'=>3)
      );
   }
}
Class Users_model extrnds MY_Model {
   protected $before_update = array( 'updated_at' );
}
after before_update_trigger i got $data like this
array (size=2)
  0 => 
    array (size=1)
      'div_id' => int 1
  'updated_at' => string '2013-03-04 13:30:14' (length=19)
and of course query builder generate incorrect sql

any suggestions?

**Comment by khyatibhojawala** [comment]
![image](https://user-images.githubusercontent.com/34775168/54351201-fc9fea00-4674-11e9-820e-d71738644fb4.png)

**Comment by khyatibhojawala** [comment]
![image](https://user-images.githubusercontent.com/34775168/54351224-09bcd900-4675-11e9-8a60-153d6100ea38.png)

still not getting any data

**Comment by khyatibhojawala** [comment]
![image](https://user-images.githubusercontent.com/34775168/54351288-2c4ef200-4675-11e9-9924-1c02face997d.png)

![image](https://user-images.githubusercontent.com/34775168/54351325-41c41c00-4675-11e9-983b-0176cff2fbf7.png)


In this query still not getting any data

**Comment by michail1982** [comment]
tnx, @khyatibhojawala
