### ISSUE TITLE
PHP Notice

### ISSUE THREAD

**Issue by paulcanning** [jamierumbelow/codeigniter-base-model#141]
I get this PHP notice when trying to use your model extension. 

Severity: Notice

Message: Undefined property: Library::$db

Filename: core/Model.php

Line Number: 51

I'm using CI v2.1.3.

**Comment by nelson6e65** [comment]
Me too. How did you solved, @paulcanning ?

**Comment by michail1982** [comment]
@nelson6e65   connect to Database before loading models

**Comment by index23** [comment]
Right, you didn't load Database Library. You can do this in Model constructor or in application/config/autoload.php if you need Database library through all your application.

**Comment by nelson6e65** [comment]
@index23 I loaded in my Model constructor, 

```php
<?php
class Example_model extends MY_Model
{
    parent::__construct();
    $this->load->database();
}
```

...but did not work. I had to load it in `Example` controller, before to load this Model.

But, then, I got same error in other Models (extending `CI_Model`), so I edit `MY_Model` constructor to load that in there (`$this->load->database()`) and I solved all troubles... at least temporally.

**Comment by index23** [comment]
@nelson6e65 

I used to load my database class in config/autoload.php. So database class is available through entire application.

**Comment by michail1982** [comment]
@index23  Are you sure?  try to run any query before load the model  or set autoinit option in database config

**Comment by nelson6e65** [comment]
@index23 Some pages do not needs to connect to database.

**Comment by index23** [comment]
@nelson6e65 

My Model constructor use database library, $this->_database = $this->db;,so you need to load database library before you call parent constructor:

    <?php
    class Example_model extends MY_Model
    {
            $this->load->database(); 
            parent::__construct();
    }
