### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by pjebs** [jamierumbelow/codeigniter-base-model#157]
Hi Jamie. I really love your model class. I am having some issues though with using multiple databases.

*In your documentation it mentions to change to a different group (as configured in database.php file) by using this command:

      public $_db_group = 'group_name';

It doesn't seem to work. I noticed your class doesn't contain a reference to that variable at all either. Is that a bug?

In the documentation you don't mention $_database at all.
However in your class you mention:

    /**
     * The database connection object. Will be set to the default
     * connection. This allows individual models to use different DBs 
     * without overwriting CI's global $this->db connection.
     */
    public $_database;

In the constructor:
$this->_database = $this->db;

Is this related to the issue since usually the we specify the database name in database.php group.

Also, if the database doesn't exist, CI spits out an error. Is there anyway to prevent that error because I want to create the database myself. i.e when extending you class:

	public function __construct()
    {
    	$success = $this->db->simple_query("CREATE DATABASE IF NOT EXISTS " . $this->_database);
    	if (!$success) ;

    	parent::__construct();
    }

**Comment by thnaeff** [comment]
In my opinion,  
```
$this->_database = $this->db;
```
should be 
```
$this->_database = (isset($this->db) ? this->db : null);
```
instead. So you would be able to assign your own database to _database after calling the constructor. Maybe as workaround you would just define a $this->db = NULL to prevent the error.

**Comment by pjebs** [comment]
I actually use laravel now. I haven't touched codeigniter for years
