### ISSUE TITLE
I can not find the uploaded file

### ISSUE THREAD

**Issue by johmcg64** [jamierumbelow/codeigniter-base-model#204]
I installed the files into my .com project on a web server. I tried demo/basic.html. It said that it uploaded the file but when I looked for the uploaded file, it was not in any of the directories in my web server. What do I need to do?

**Comment by jamierumbelow** [comment]
Hi @johmcg64 – I'm sorry, there isn't such a file! Can you step me through what you're having trouble with?

**Comment by johmcg64** [comment]
Thank you. When I run
http://u-soln.com/FileDrop-master/FileDrop-master/demo/basic.html it says
that it uploads a file, profileimage.png, but when I look in the
directories, i can not find it. u-soln.com is the web site that I loaded
your plug in into.

John

**Comment by jamierumbelow** [comment]
Sorry John – this is a different plugin. Over here we're developing a base CRUD model for CodeIgniter applications. You might want to [submit your issue over here instead](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0CCEQFjAA&url=https%3A%2F%2Fgithub.com%2FProgerXP%2FFileDrop&ei=x1NYVf3VI6bB7gaasIKgDw&usg=AFQjCNFAUJmmUnHoPcJyr69XDKsSbuUPeA&sig2=UQBXMjpQOfoa_XurUVca5A&bvm=bv.93564037,d.ZGU).

**Comment by johmcg64** [comment]
No

**Comment by johmcg64** [comment]
I am sorry I said "No." Thank you.
