### ISSUE TITLE
Nested relations is possible?

### ISSUE THREAD

**Issue by byybora** [jamierumbelow/codeigniter-base-model#206]
**Reservations_model**
````
public $belongs_to = array('vehicle' => 
	array( 
		'model' => 'vehicles_model',
		'primary_key' => 'vehicle_id'
	)
);		
````

**Vehicles_model**
````
public $belongs_to = array('type' => 
	array( 
		'model' => 'vehicle_types_model',
		'primary_key' => 'type_id'
	) 
);
````

I can get the `$reservation->vehicle->id` but  i want to access `$reservation->vehicle->type->id`. 

Is it possible deeply relations?

**Comment by jamierumbelow** [comment]
Unfortunately not – I'd do a manual `JOIN`; the relationship functionality is not supposed to be much more than basic accessing.
