### ISSUE TITLE
Before delete - update_all issue

### ISSUE THREAD

**Issue by gorankrgovic** [jamierumbelow/codeigniter-base-model#214]
I'm using the MY_Model class and its awesome, but can someone please explain, how to use the update_all with before_delete callback. I have, for example, the page table. When I delete the article, I need to update all records in the same table which has the deleted article ID as the parent_id . I'm sorry but there is no explanation on how to use the before_delete with update_all function, so can somebody please explain me how to implement it. 
Thanks

**Comment by musman92** [comment]
Befote_deleye =array('update_function');
Create fn with name update_function and write your desire code

**Comment by michail1982** [comment]
@gorankrgovic  you must consider, before delete params can be few types depends on method( delete, delete_by, delete many, delete_many_by)  and soft_delete flag

**Comment by gorankrgovic** [comment]
Thank you guys
