### ISSUE TITLE
Clarification on Order By

### ISSUE THREAD

**Issue by gautamsawala** [jamierumbelow/codeigniter-base-model#215]
I was wondering if there is someway to order the results on a given row, for example on data and time stamp?

**Comment by vsogrimen** [comment]
If i understand your question correctly, I think you can do it like this:
$this->model->order_by(array('some_column' => 'ASC')

**Comment by gautamsawala** [comment]
It Works!! (Y) 

Thanks

**Comment by vsogrimen** [comment]
Good to hear that!! You're welcome :smile:

**Comment by adeelmughal4u** [comment]
With the following
$this->remote_jobs->get_many_by($jobs_params);

I am getting below query
SELECT * FROM `hm_jobs` WHERE `company_id` = '1' AND `user_id` = '6'

I want to append order by with this query, how I can do?
