### ISSUE TITLE
Temporarily disable soft delete?

### ISSUE THREAD

**Issue by paulcanning** [jamierumbelow/codeigniter-base-model#233]
I am using soft deletes to effectively "archive" records (simply because it was quicker to setup)

However, I also need to actually delete the records later on.

How can I temporarily disable the soft delete for a model method?

Or is the solution simply, don't use soft deletes incorrectly?

**Comment by jamierumbelow** [comment]
You could write a small wrapper function to temporarily disable soft delete, like this:

```php
public function disableSoftDelete(callable $fn)
{
    $this->soft_delete = false;
    $result = call_user_func($fn);
    $this->soft_delete = true;

    return $result;
}
```

Then run your query within that closure:

```php
$postId = 1;

$this->user->disableSoftDelete(function () use ($postId)
{
    $this->delete($postId);
});
```

Or you could simply define a proper delete method – remember, you're free to call `$this->_database` directly!

```php
public function reallyDelete($id)
{
    return $this->_database->where($this->primary_key, $id)
        ->delete($this->_table);
}
```

**Comment by paulcanning** [comment]
I ended up just removing the soft delete and updating the archived flag properly. That way I can properly delete rows without any extra hacks :)
